service: serverless-order-app

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

  environment:
    TABLE_NAME: OrdersTable
    QUEUE_URL:
      Ref: OrdersQueue
    TOPIC_ARN:
      Ref: OrdersTopic

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource: "*"

        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
          Resource: "*"

        - Effect: Allow
          Action:
            - sns:Publish
          Resource: "*"

functions:
  createOrder:
    handler: functions/createOrder.handler
    events:
      - http:
          path: orders
          method: post

  processOrder:
    handler: functions/processOrder.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - OrdersQueue
              - Arn

  notifyUser:
    handler: functions/notifyUser.handler
    events:
      - sns:
          arn:
            Ref: OrdersTopic

resources:
  Resources:
    OrdersQueue:
      Type: AWS::SQS::Queue

    OrdersTopic:
      Type: AWS::SNS::Topic

    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: OrdersTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
